spring:
  config:
    activate:
      on-profile: "qa"


build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Youssef - Developer"
    email: "youssef@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932